type TranslateReplacements = Record<string, unknown>

const translations: Record<string, string> = {
  '<custom type>': '<自定义类型>',
  '<empty>': '<空>',
  '<none>': '<无>',
  '1 hour and 30 minutes': '1 小时 30 分钟',
  '14 days': '14 天',
  '15 seconds': '15 秒',
  'A cycle defined as ISO 8601 repeating intervals format, or a cron expression.': '使用 ISO 8601 重复间隔格式或 cron 表达式定义周期。',
  'A cycle defined as ISO 8601 repeating intervals format.': '使用 ISO 8601 重复间隔格式定义周期。',
  'A FEEL expression that determines whether the event should trigger. ': '用于判断事件是否触发的 FEEL 表达式。',
  'A specific point in time defined as ISO 8601 combined date and time representation.': '使用 ISO 8601 日期时间格式定义的具体时间点。',
  'A time duration defined as ISO 8601 durations format.': '使用 ISO 8601 duration 格式定义的时间段。',
  'About conditional events.': '关于条件事件。',
  'Activate create/remove space tool': '启用创建/删除空间工具',
  'Activate global connect tool': '启用全局连接工具',
  'Activate hand tool': '启用手型拖动画布工具',
  'Activate lasso tool': '启用套索选择工具',
  'Active elements': '活动元素',
  'Active elements collection': '活动元素集合',
  'Activity reference': '活动引用',
  'Add input mappings to control what is passed to the activity as local variables. ': '添加输入映射，用于控制传递给活动的本地变量。',
  'Add lane above': '在上方添加泳道',
  'Add lane below': '在下方添加泳道',
  'Add output mappings to control which variables are merged back into the process scope. ': '添加输出映射，用于控制哪些变量合并回流程作用域。',
  'Add text annotation': '添加文本注释',
  'Ad-hoc subprocess documentation': '即席子流程文档',
  After: '之后',
  'Align elements': '对齐元素',
  'Align elements ': '对齐元素',
  'Append compensation activity': '追加补偿活动',
  'Append conditional intermediate catch event': '追加条件中间捕获事件',
  'Append end event': '追加结束事件',
  'Append gateway': '追加网关',
  'Append intermediate/boundary event': '追加中间/边界事件',
  'Append message intermediate catch event': '追加消息中间捕获事件',
  'Append receive task': '追加接收任务',
  'Append signal intermediate catch event': '追加信号中间捕获事件',
  'Append task': '追加任务',
  'Append timer intermediate catch event': '追加定时器中间捕获事件',
  Assignee: '处理人',
  assignment: '分配',
  Assignment: '任务分配',
  'Assignment type': '分配类型',
  'Asynchronous after': '异步后续',
  'Asynchronous before': '异步前置',
  'Asynchronous continuations': '异步延续',
  Before: '之前',
  Binding: '绑定方式',
  boolean: '布尔',
  BPMN: 'BPMN',
  'Business key': '业务键',
  'Business key expression': '业务键表达式',
  'Business rule task documentation': '业务规则任务文档',
  'Call activity documentation': '调用活动文档',
  'Called decision': '被调用决策',
  'Called element': '被调用元素',
  'Camunda Form': 'Camunda 表单',
  'Camunda Form (embedded)': 'Camunda 表单（内嵌）',
  'Camunda Form (linked)': 'Camunda 表单（链接）',
  'Camunda Forms': 'Camunda 表单',
  'Camunda user task': 'Camunda 用户任务',
  'Cancel remaining instances': '取消剩余实例',
  'Candidate groups': '候选组',
  'Candidate starter': '候选启动者',
  'Candidate starter groups': '候选启动组',
  'Candidate starter users': '候选启动用户',
  'Candidate users': '候选用户',
  'Case ref': '案例引用',
  'Change element': '更改元素',
  Class: '类',
  CMMN: 'CMMN',
  Code: '代码',
  'Code variable': '代码变量',
  'collectEntries (List<Object>)': 'collectEntries（List<Object>）',
  Collection: '集合',
  Compensation: '补偿',
  complete: '完成',
  Completion: '完成',
  'Completion condition': '完成条件',
  Condition: '条件',
  'Condition expression': '条件表达式',
  'Condition Expression': '条件表达式',
  'Conditional event documentation': '条件事件文档',
  'Conditions documentation': '条件文档',
  Config: '配置',
  'Configure the message that the task waits for. ': '配置该任务等待的消息。',
  'Configure the message that this event waits for. ': '配置该事件等待的消息。',
  'Configure the message that will start this process instance. ': '配置将启动此流程实例的消息。',
  'Configure the message that will trigger this boundary event. ': '配置将触发此边界事件的消息。',
  'Connect to other element': '连接到其它元素',
  'Connect using association': '使用关联连接',
  'Connect using data input association': '使用数据输入关联连接',
  'Connector ID': '连接器 ID',
  'Connector inputs': '连接器输入',
  'Connector outputs': '连接器输出',
  Constraints: '约束',
  Create: '创建',
  create: '创建',
  'Create data object reference': '创建数据对象引用',
  'Create data store reference': '创建数据存储引用',
  'Create end event': '创建结束事件',
  'Create expanded sub-process': '创建展开的子流程',
  'Create gateway': '创建网关',
  'Create group': '创建分组',
  'Create intermediate/boundary event': '创建中间/边界事件',
  'Create new ...': '新建...',
  'Create pool/participant': '创建池/参与者',
  'Create start event': '创建开始事件',
  'Create task': '创建任务',
  'Created in': '创建于',
  'Custom form key': '自定义 formKey',
  'Custom type': '自定义类型',
  Cycle: '周期',
  date: '日期',
  Date: '日期',
  'Decision ID': '决策 ID',
  'Decision reference': '决策引用',
  'Default value': '默认值',
  'Define a boolean condition expression that defines when this flow is taken. ': '定义用于判断此流转何时被采用的布尔条件表达式。',
  'Define a collection of elements which will be activated when the ad-hoc subprocess is reached. ': '定义到达即席子流程时将被激活的元素集合。',
  'Define an error code (e.g. ': '定义错误代码（例如 ',
  'Define an input collection expression that defines the collection to iterate over (e.g. ': '定义用于迭代的输入集合表达式（例如 ',
  'Define the completion behavior of an ad-hoc subprocess. If no completion condition is set, it will be completed after all active elements have been completed. ': '定义即席子流程的完成行为。若未设置完成条件，则所有活动元素完成后即视为完成。',
  'Define the decision to evaluate and how to map back the evaluation result. ': '定义要评估的决策以及评估结果如何映射回流程。',
  'Define the ID of the process to call (e.g. ': '定义要调用的流程 ID（例如 ',
  'Define the name of the variable that will contain the error code.': '定义保存错误代码的变量名。',
  'Define the name of the variable that will contain the error message.': '定义保存错误消息的变量名。',
  'Define the name of the variable that will contain the escalation code.': '定义保存升级代码的变量名。',
  'Define who the task is assigned to. One or all of the following attributes can be specified simultaneously. ': '定义任务分配给谁。可以同时指定以下一个或多个属性。',
  'Delegate Class': '委托类',
  'Delegate Expression': '委托表达式',
  'Delegate expression': '委托表达式',
  'Delegate Variable Mapping': '委托变量映射',
  Delete: '删除',
  delete: '删除',
  deployment: '部署',
  'Deployment binding': '部署绑定',
  'Distribute elements horizontally': '水平分布元素',
  'Distribute elements vertically': '垂直分布元素',
  'Divide into three lanes': '拆分为三条泳道',
  'Divide into two lanes': '拆分为两条泳道',
  'DMN decision': 'DMN 决策',
  Documentation: '文档',
  'Documentation: Timer events': '文档：定时器事件',
  'Documentation: Variable events': '文档：变量事件',
  'Due date': '到期日期',
  Duration: '持续时间',
  'Element documentation': '元素文档',
  'Element variable': '元素变量',
  'Embedded or External Task Forms': '内嵌或外部任务表单',
  end: '结束',
  enum: '枚举',
  Error: '错误',
  'Error event documentation': '错误事件文档',
  Errors: '错误',
  Escalation: '升级',
  'Evaluate a business rule, for example a DMN decision. To add a custom implementation, use a job worker. ': '评估业务规则，例如 DMN 决策。如需自定义实现，请使用作业工作器。',
  'Event type': '事件类型',
  'every 10 seconds, up to 5 times': '每 10 秒一次，最多 5 次',
  'every day, infinitely': '每天一次，无限重复',
  'every hour on the hour from 9-5 p.m. UTC Monday-Friday': 'UTC 周一至周五 9 点到 17 点每小时整点一次',
  Exclusive: '排他',
  Executable: '可执行',
  'Execute this task for each element of a given collection. ': '对给定集合中的每个元素执行此任务。',
  'Execution listeners': '执行监听器',
  Expression: '表达式',
  'Extension properties': '扩展属性',
  'External form reference': '外部表单引用',
  'External resource': '外部资源',
  'External task': '外部任务',
  'FEEL expression': 'FEEL 表达式',
  'Field injection': '字段注入',
  'Field injections': '字段注入',
  'Follow up date': '跟进日期',
  Form: '表单',
  'Form fields': '表单字段',
  'Form ID': '表单 ID',
  'Form JSON configuration': '表单 JSON 配置',
  'Form key': 'formKey',
  'Form reference': '表单引用',
  Format: '格式',
  Forms: '表单',
  General: '常规',
  'Generated Task Forms': '生成式任务表单',
  'Global error reference': '全局错误引用',
  'Global escalation reference': '全局升级引用',
  'Global message reference': '全局消息引用',
  'Global signal reference': '全局信号引用',
  Headers: '请求头',
  'HELLO {you}': '你好 {you}',
  'History cleanup': '历史清理',
  'How to configure a timer': '如何配置定时器',
  ID: 'ID',
  'ID must be a valid QName.': 'ID 必须是有效的 QName。',
  'ID must be unique.': 'ID 必须唯一。',
  'ID must not be empty.': 'ID 不能为空。',
  'ID must not contain prefix.': 'ID 不能包含前缀。',
  'ID must not contain spaces.': 'ID 不能包含空格。',
  'Identifier computed from the process context that is used to correlate an incoming message (e.g. ': '从流程上下文计算出的标识符，用于关联传入消息（例如 ',
  'If turned on, all variables from the child process instance will be propagated to the parent process instance.': '开启后，子流程实例中的所有变量都会传播到父流程实例。',
  'If turned on, all variables from the parent process instance will be propagated to the child process instance.': '开启后，父流程实例中的所有变量都会传播到子流程实例。',
  'Implement a script task using an inline FEEL expression. To add a custom implementation, use a job worker. ': '使用内联 FEEL 表达式实现脚本任务。如需自定义实现，请使用作业工作器。',
  'Implement a user task managed by Camunda. To add a custom implementation, use a job worker. ': '实现由 Camunda 管理的用户任务。如需自定义实现，请使用作业工作器。',
  Implementation: '实现',
  'Implementation type': '实现类型',
  'In mapping propagation': '输入映射传播',
  'In mappings': '输入映射',
  Initiator: '启动人',
  'Inline script': '内联脚本',
  'Input collection': '输入集合',
  'Input element': '输入元素',
  'Input mapping': '输入映射',
  'Input mappings documentation': '输入映射文档',
  'Input propagation': '输入传播',
  Inputs: '输入',
  'Java class': 'Java 类',
  'Job execution': '作业执行',
  'Job type': '作业类型',
  'Job worker': '作业工作器',
  Key: '键',
  Label: '标签',
  latest: '最新',
  'Latest binding': '最新绑定',
  'Learn how to define conditions.': '了解如何定义条件。',
  'Learn more.': '了解更多。',
  Link: '链接',
  'Link a form created with the Camunda Forms editor. To associate a custom form, application, or URL to the user task, specify an external reference. ': '链接使用 Camunda Forms 编辑器创建的表单。若要关联自定义表单、应用或 URL，请为用户任务指定外部引用。',
  'Link or embed a form created with the Camunda Forms editor. To associate a custom form, application, or URL to the user task, specify a form key. ': '链接或内嵌使用 Camunda Forms 编辑器创建的表单。若要关联自定义表单、应用或 URL，请为用户任务指定 formKey。',
  List: '列表',
  'List values': '列表值',
  'Listener ID': '监听器 ID',
  'Listener type': '监听器类型',
  Local: '本地',
  long: '长整型',
  Loop: '循环',
  'Loop cardinality': '循环基数',
  Map: '映射',
  'Map decision result': '映射决策结果',
  'Map entries': '映射项',
  Message: '消息',
  'Message boundary event documentation': '消息边界事件文档',
  'Message catch event documentation': '消息捕获事件文档',
  'Message start event documentation': '消息开始事件文档',
  'Message throw event documentation': '消息抛出事件文档',
  'Message variable': '消息变量',
  'Multi instance documentation': '多实例文档',
  'Multi-instance': '多实例',
  'Multiple elements are selected. Select a single element to edit its properties.': '已选择多个元素。请选择单个元素以编辑其属性。',
  Name: '名称',
  'Number of days before this resource is being cleaned up. If specified, takes precedence over the engine configuration.': '此资源被清理前保留的天数。如已指定，将优先于引擎配置。',
  Off: '关',
  On: '开',
  'Open {element}': '打开 {element}',
  'Otherwise, only variables defined via input mappings will be propagated.': '否则，仅传播通过输入映射定义的变量。',
  'Otherwise, only variables defined via output mappings will be propagated.': '否则，仅传播通过输出映射定义的变量。',
  'Out mapping propagation': '输出映射传播',
  'Out mappings': '输出映射',
  'Output collection': '输出集合',
  'Output element': '输出元素',
  'Output mapping': '输出映射',
  'Output mappings documentation': '输出映射文档',
  'Output propagation': '输出传播',
  Outputs: '输出',
  'Parallel multi-instance': '并行多实例',
  'Participant multiplicity': '参与者多重性',
  'Participant Name': '参与者名称',
  Priority: '优先级',
  'Process documentation': '流程文档',
  'Process ID': '流程 ID',
  'Process name': '流程名称',
  'Process variables': '流程变量',
  'Propagate all child process variables': '传播所有子流程变量',
  'Propagate all parent process variables': '传播所有父流程变量',
  'Propagate all variables': '传播所有变量',
  Properties: '属性',
  'Receive task message documentation': '接收任务消息文档',
  'Refers to the process variable name': '引用流程变量名',
  Resource: '资源',
  'Result variable': '结果变量',
  'resultList (List<Map<String, Object>>)': 'resultList（List<Map<String, Object>>）',
  Retries: '重试次数',
  'Retry time cycle': '重试时间周期',
  Scope: '作用域',
  Script: '脚本',
  'Script task documentation': '脚本任务文档',
  'Script type': '脚本类型',
  'Search in diagram': '在图中搜索',
  'Select an element to edit its properties.': '请选择一个元素以编辑其属性。',
  'Send task documentation': '发送任务文档',
  'Sequential multi-instance': '顺序多实例',
  'Service task documentation': '服务任务文档',
  Signal: '信号',
  'singleEntry (TypedValue)': 'singleEntry（TypedValue）',
  'singleResult (Map<String, Object>)': 'singleResult（Map<String, Object>）',
  Source: '来源',
  'Source expression': '来源表达式',
  'Specifies the priority of a user task. Must be an integer between 0 and 100. If no value is provided, the default value is 50. ': '指定用户任务优先级。必须是 0 到 100 之间的整数。若未提供值，默认值为 50。',
  'Specify more than one group as a comma separated list.': '多个组请使用逗号分隔。',
  'Specify more than one user as a comma separated list.': '多个用户请使用逗号分隔。',
  'Specify more than one variable change event as a comma separated list. Variable change events are:': '多个变量变更事件请使用逗号分隔。变量变更事件包括：',
  'Specify the condition that triggers this event. ': '指定触发此事件的条件。',
  'Specify which job workers handle the event work. ': '指定哪些作业工作器处理该事件工作。',
  'Specify which job workers handle the task work to evaluate business rules. ': '指定哪些作业工作器处理业务规则评估任务。',
  'Specify which job workers handle the task work to execute a script. ': '指定哪些作业工作器处理脚本执行任务。',
  'Specify which job workers handle the task work to execute a service (e.g. ': '指定哪些作业工作器处理服务执行任务（例如 ',
  'Specify which job workers handle the task work to send a message (e.g. ': '指定哪些作业工作器处理消息发送任务（例如 ',
  start: '开始',
  'Start initiator': '启动发起人',
  'Start typing "${}" to create an expression.': '输入 "${}" 开始创建表达式。',
  Startable: '可启动',
  string: '字符串',
  String: '字符串',
  'String or expression': '字符串或表达式',
  'Subscription correlation key': '订阅关联键',
  'Subscription correlation key documentation': '订阅关联键文档',
  take: '采用',
  Target: '目标',
  'Task definition': '任务定义',
  'Task listeners': '任务监听器',
  Tasklist: '任务列表',
  'Tenant ID': '租户 ID',
  'The due date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).': '到期日期，可填写 EL 表达式（例如 ${someDate}）或 ISO 日期（例如 2015-06-26T09:54:00）。',
  'The follow up date as an EL expression (e.g. ${someDate}) or an ': '跟进日期，可填写 EL 表达式（例如 ${someDate}）或 ',
  'The number of times the engine tries executing this activity if a worker signals a failure. The default is three.': '当工作器报告失败时，引擎尝试执行此活动的次数。默认值为 3。',
  'This maps to the process definition key.': '这里映射到流程定义 key。',
  'Throw expression': '抛出表达式',
  'Time to live': '存活时间',
  timeout: '超时',
  Timer: '定时器',
  'Timer documentation': '定时器文档',
  'To collect the output define the output collection and the output element expressions. ': '如需收集输出，请定义输出集合和输出元素表达式。',
  'Toggle non-interrupting': '切换为非中断',
  Topic: '主题',
  Type: '类型',
  update: '更新',
  Update: '更新',
  'User assignment': '用户分配',
  'User task documentation': '用户任务文档',
  'User task form documentation': '用户任务表单文档',
  'User task priority documentation': '用户任务优先级文档',
  'Uses the most recent deployed resource with the given version tag.': '使用带指定版本标签的最新已部署资源。',
  'Uses the most recent deployed resource.': '使用最新已部署资源。',
  'Uses the resource found in the same deployment.': '使用同一部署中的资源。',
  'UTC plus 2 hours zone offset': 'UTC+2 时区偏移',
  'UTC time': 'UTC 时间',
  Value: '值',
  Values: '值',
  'Variable assignment value': '变量赋值',
  'Variable events': '变量事件',
  'Variable events that trigger the condition evaluation. ': '触发条件评估的变量事件。',
  'Variable name': '变量名',
  version: '版本',
  Version: '版本',
  'Version tag': '版本标签',
  'version tag': '版本标签',
  'Version tag binding': '版本标签绑定',
  'Version tag by which the called decision will be referenced.': '被调用决策引用使用的版本标签。',
  'Version tag by which the called process will be referenced.': '被调用流程引用使用的版本标签。',
  'Version tag by which the linked form will be referenced.': '被链接表单引用使用的版本标签。',
  'Version tag by which this process can be referenced.': '此流程可被引用的版本标签。',
  versionTag: '版本标签',
  'Wait for completion': '等待完成',

  'Ad Hoc Sub Process': '即席子流程',
  'Boundary Event': '边界事件',
  'Business Rule Task': '业务规则任务',
  'Call Activity': '调用活动',
  'Collaboration': '协作',
  'Complex Gateway': '复杂网关',
  'Conditional Event': '条件事件',
  'Data Object Reference': '数据对象引用',
  'Data Store Reference': '数据存储引用',
  'End Event': '结束事件',
  'Event Based Gateway': '事件网关',
  'Exclusive Gateway': '排他网关',
  'Expanded Sub Process': '展开的子流程',
  'Group': '分组',
  'Inclusive Gateway': '包容网关',
  'Intermediate Catch Event': '中间捕获事件',
  'Intermediate Throw Event': '中间抛出事件',
  'Lane': '泳道',
  'Manual Task': '手工任务',
  'Parallel Gateway': '并行网关',
  'Participant': '参与者',
  'Receive Task': '接收任务',
  'Script Task': '脚本任务',
  'Send Task': '发送任务',
  'Sequence Flow': '顺序流',
  'Service Task': '服务任务',
  'Start Event': '开始事件',
  'Sub Process': '子流程',
  'Task': '任务',
  'Text Annotation': '文本注释',
  'Transaction': '事务',
  'User Task': '用户任务'
}

function interpolate(template: string, replacements?: TranslateReplacements): string {
  if (!replacements) return template

  return template.replace(/{([^}]+)}/g, (_, key: string) => {
    const value = replacements[key]
    return value === undefined || value === null ? `{${key}}` : String(value)
  })
}

export function translate(template: string, replacements?: TranslateReplacements): string {
  return interpolate(translations[template] || template, replacements)
}

const BpmnChineseTranslateModule = {
  translate: ['value', translate]
}

export default BpmnChineseTranslateModule
